name: matgary
description: A full-stack e-commerce app with Flutter and Supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Backend & Authentication
  supabase_flutter: ^1.10.25
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # UI Components
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  
  # Payments
  flutter_stripe: ^9.5.0+1
  
  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # Location & Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700